-- Task-08: create collection source and task tables for admin management

CREATE TABLE IF NOT EXISTS biz_collection_source (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    source_name VARCHAR(255) NOT NULL COMMENT 'Source name',
    source_category VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Source category code',
    source_url VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Source endpoint or address',
    access_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Access type code',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT 'Enable flag: 1 enabled, 0 disabled',
    status VARCHAR(32) NOT NULL DEFAULT 'running' COMMENT 'Source status code',
    region_scope VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Region scope text',
    owner_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Owner name',
    latest_collect_time DATETIME NULL COMMENT 'Latest collect time',
    description VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Source description',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Created by',
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Updated by',
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Remark',
    PRIMARY KEY (id),
    UNIQUE KEY uk_collection_source_name (source_name),
    KEY idx_collection_source_category (source_category),
    KEY idx_collection_source_access_type (access_type),
    KEY idx_collection_source_enabled (enabled),
    KEY idx_collection_source_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Collection source';

CREATE TABLE IF NOT EXISTS biz_collection_task (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    task_name VARCHAR(255) NOT NULL COMMENT 'Task name',
    source_id BIGINT NOT NULL COMMENT 'Collection source ID',
    task_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Task type code',
    cron_expr VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Cron expression or schedule rule',
    frequency_desc VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Human readable frequency',
    enabled TINYINT NOT NULL DEFAULT 1 COMMENT 'Enable flag: 1 enabled, 0 disabled',
    run_status VARCHAR(32) NOT NULL DEFAULT 'running' COMMENT 'Run status code',
    latest_result VARCHAR(32) NOT NULL DEFAULT 'success' COMMENT 'Latest run result code',
    latest_run_time DATETIME NULL COMMENT 'Latest run time',
    record_count BIGINT NOT NULL DEFAULT 0 COMMENT 'Collected record count',
    success_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00 COMMENT 'Success rate',
    description VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Task description',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Created by',
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Updated by',
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Remark',
    PRIMARY KEY (id),
    UNIQUE KEY uk_collection_task_name (task_name),
    KEY idx_collection_task_source_id (source_id),
    KEY idx_collection_task_type (task_type),
    KEY idx_collection_task_enabled (enabled),
    KEY idx_collection_task_run_status (run_status),
    CONSTRAINT fk_collection_task_source_id FOREIGN KEY (source_id) REFERENCES biz_collection_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Collection task';
