-- Task-09: create data package, package file, and delivery record tables

CREATE TABLE IF NOT EXISTS biz_data_package (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    package_name VARCHAR(255) NOT NULL COMMENT 'Data package name',
    package_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Data package type code',
    stat_month VARCHAR(16) NOT NULL DEFAULT '' COMMENT 'Statistic month, such as 2026-04',
    region_scope VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Region scope text',
    file_count INT NOT NULL DEFAULT 0 COMMENT 'Package file count',
    total_size BIGINT NOT NULL DEFAULT 0 COMMENT 'Package total size in bytes',
    status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'Package status: draft/published',
    publish_version INT NOT NULL DEFAULT 0 COMMENT 'Package publish version',
    publish_time DATETIME NULL COMMENT 'Latest publish time',
    published_by_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Latest publisher name',
    publish_note VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Latest publish note',
    description VARCHAR(1000) NOT NULL DEFAULT '' COMMENT 'Package description',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Created by',
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Updated by',
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Remark',
    PRIMARY KEY (id),
    UNIQUE KEY uk_data_package_name_month (package_name, stat_month),
    KEY idx_data_package_type (package_type),
    KEY idx_data_package_status (status),
    KEY idx_data_package_publish_time (publish_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Data package';

CREATE TABLE IF NOT EXISTS biz_data_package_file (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    package_id BIGINT NOT NULL COMMENT 'Data package ID',
    file_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'File name',
    file_path VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Logical file path',
    file_size BIGINT NOT NULL DEFAULT 0 COMMENT 'File size in bytes',
    file_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'File type',
    checksum VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'File checksum',
    storage_type VARCHAR(64) NOT NULL DEFAULT 'LOCAL' COMMENT 'Reserved storage type',
    storage_bucket VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Reserved storage bucket',
    storage_object_key VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Reserved storage object key',
    download_url VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Reserved download URL',
    sort_order INT NOT NULL DEFAULT 0 COMMENT 'Display order',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Created by',
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Updated by',
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Remark',
    PRIMARY KEY (id),
    KEY idx_data_package_file_package_id (package_id),
    KEY idx_data_package_file_sort_order (sort_order),
    CONSTRAINT fk_data_package_file_package_id FOREIGN KEY (package_id) REFERENCES biz_data_package (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Data package file';

CREATE TABLE IF NOT EXISTS biz_delivery_record (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    delivery_type VARCHAR(64) NOT NULL DEFAULT 'data_package' COMMENT 'Delivery type code',
    related_id BIGINT NOT NULL COMMENT 'Related business ID',
    related_name VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Related business name snapshot',
    related_version INT NOT NULL DEFAULT 0 COMMENT 'Related business version snapshot',
    receiver_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Receiver name',
    receiver_org VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Receiver organization',
    contact_phone VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Receiver contact phone',
    delivery_time DATETIME NOT NULL COMMENT 'Delivery time',
    delivery_method VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Delivery method code',
    description VARCHAR(1000) NOT NULL DEFAULT '' COMMENT 'Delivery description',
    created_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Created by',
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_by BIGINT NOT NULL DEFAULT 0 COMMENT 'Updated by',
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag: 0 active, 1 deleted',
    remark VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Remark',
    PRIMARY KEY (id),
    KEY idx_delivery_record_type (delivery_type),
    KEY idx_delivery_record_related_id (related_id),
    KEY idx_delivery_record_method (delivery_method),
    KEY idx_delivery_record_delivery_time (delivery_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Delivery record';
